import Navbar from './navbar';
import Head from 'next/head';
import { GlobalStyle } from '../../styles/app.styles';
import { useEffect, useState } from 'react';

import { useRouter } from 'next/router';

const Layout = (props) => {
  const router = useRouter();
  console.log(router.asPath);

  useEffect(() => {
    console.log('initial');
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <GlobalStyle />
      <main>{props.children}</main>
    </>
  );
};

export default Layout;
